/** @type {import('@remix-run/dev').AppConfig} */
module.exports = {
  future: {
    v2_routeConvention: true,
  },
  ignoredRouteFiles: ['**/.*'],
  publicPath: '/_static/build/',
  server: './server.js',
  serverBuildPath: 'server/index.js',
  // appDirectory: "app",
  // assetsBuildDirectory: "public/build",
  serverDependenciesToBundle: [
    'mdx-bundler',
    /@mdx-js\/*/,
    'remark-frontmatter',
    '@esbuild-plugins',
    /mdast-.*/,
    /micromark/,
    /micromark-.*/,
    /vfile*/,
    /unist-.*/,
    /estree-.*/,
    /remark-.*/,
    /comma-.*/,
    'unified',
    /hast-.*/,
    /property-.*/,
    /space-.*/,
    'zwitch',
    'fault',
    'bail',
    'trough',
    'ccount',
    /parse-.*/,
    /stringify-.*/,
    /decode-.*/,
    /character-.*/,
    /is-.*/,
    'remark-gfm',
    /micromark-.*/,
    /mdast-.*/,
    'ccount',
    /unist-.*/,
    'decode-named-character-reference',
    'character-entities',
    'markdown-table',
  ],
};
