/** @type {import('@remix-run/dev').AppConfig} */
module.exports = {
  future: {
    v2_routeConvention: true,
  },
  ignoredRouteFiles: ['**/.*'],
  publicPath: '/_static/build/',
  server: './server.js',
  serverBuildPath: 'server/index.js',
  // appDirectory: "app",
  // assetsBuildDirectory: "public/build",
  serverDependenciesToBundle: [
    '@esbuild-plugins',
    'fault',
    'vfile',
    'unified',
    '@babel/runtime',
    'remark-frontmatter',
    '@esbuild-plugins',
    'fetch-blob',
    'formdata-polyfill',
    'bail',
    'ccount',
    'hast-util-to-estree',
    'is-plain-obj',
    'markdown-table',
    'trim-lines',
    'mdx-bundler',
    'escape-string-regexp',
    'node-fetch',
    'comma-separated-tokens',
    'is-decimal',
    'is-hexadecimal',
    'is-alphanumerical',
    'zswitch',
    'property-information',
    'micromark-extension-frontmatter',
    'mdast-util-frontmatter',
    'micromark-extension-frontmatter',
    'micromark-util-character',
    'remark-mdx-frontmatter',
    'estree-util-is-identifier-name',
  ],
};
